/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

    import Menu.DogeToIDR;
    import Menu.DollarToIDR;
    import Menu.Temperture;
    import Menu.RupiahToPertamina;
    import Menu.ToolbarMenu;

/**
 *
 * @author Asus
 */
public class TugasMenu extends javax.swing.JFrame {

    /**
     * Creates new form TugasMenu
     */
    public TugasMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        labelSuhu = new javax.swing.JLabel();
        temperatureButton = new javax.swing.JButton();
        labelPertamina = new javax.swing.JLabel();
        cryptoButton = new javax.swing.JButton();
        labelMataUang = new javax.swing.JLabel();
        currencyButton = new javax.swing.JButton();
        temperatureButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuOpen = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuImport = new javax.swing.JMenuItem();
        menuExport = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuConvert = new javax.swing.JMenu();
        menuTemperature = new javax.swing.JMenuItem();
        menuDollar = new javax.swing.JMenuItem();
        menuDoge = new javax.swing.JMenuItem();
        menuPertamina = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuUndo = new javax.swing.JMenuItem();
        menuRedo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuCopy = new javax.swing.JMenuItem();
        menuCut = new javax.swing.JMenuItem();
        menuPaste = new javax.swing.JMenuItem();
        menuDelete = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuFind = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuUpdate = new javax.swing.JMenuItem();
        menuReport = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(68, 68, 68));
        setForeground(new java.awt.Color(68, 68, 68));

        jPanel1.setBackground(new java.awt.Color(68, 68, 68));

        labelJudul.setBackground(new java.awt.Color(190, 190, 190));
        labelJudul.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(190, 190, 190));
        labelJudul.setText("SELECT CONVERSION (PILIH KONVERSI)");

        labelSuhu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelSuhu.setForeground(new java.awt.Color(190, 190, 190));
        labelSuhu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSuhu.setText("TEMPERATURE (SUHU)");
        labelSuhu.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        temperatureButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/suhu.png"))); // NOI18N
        temperatureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureButtonActionPerformed(evt);
            }
        });

        labelPertamina.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelPertamina.setForeground(new java.awt.Color(190, 190, 190));
        labelPertamina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPertamina.setText("PERTAMINA");
        labelPertamina.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cryptoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crypto.png"))); // NOI18N
        cryptoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cryptoButtonActionPerformed(evt);
            }
        });

        labelMataUang.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelMataUang.setForeground(new java.awt.Color(190, 190, 190));
        labelMataUang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMataUang.setText("CURRENCY (MATA UANG)");
        labelMataUang.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        currencyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/currency.png"))); // NOI18N
        currencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyButtonActionPerformed(evt);
            }
        });

        temperatureButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pertamina.png"))); // NOI18N
        temperatureButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(labelJudul))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(temperatureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMataUang, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currencyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cryptoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPertamina, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temperatureButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSuhu)
                    .addComponent(labelPertamina, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMataUang, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temperatureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(currencyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cryptoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(temperatureButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(68, 68, 68));

        jMenu1.setBackground(new java.awt.Color(68, 68, 68));
        jMenu1.setText("File");

        menuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/New-file-icon (2).png"))); // NOI18N
        menuNew.setText("New");
        jMenu1.add(menuNew);
        jMenu1.add(jSeparator2);

        menuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-document-open-icon.png"))); // NOI18N
        menuOpen.setText("Open");
        jMenu1.add(menuOpen);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save-icon.png"))); // NOI18N
        menuSave.setText("Save");
        jMenu1.add(menuSave);
        jMenu1.add(jSeparator3);

        menuImport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/import-icon.png"))); // NOI18N
        menuImport.setText("Import");
        jMenu1.add(menuImport);

        menuExport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/export-icon.png"))); // NOI18N
        menuExport.setText("Export");
        jMenu1.add(menuExport);
        jMenu1.add(jSeparator5);

        menuConvert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document-convert-icon.png"))); // NOI18N
        menuConvert.setText("Convert");

        menuTemperature.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        menuTemperature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Temperature-2-icon.png"))); // NOI18N
        menuTemperature.setText("Celcius To Fahrenheit");
        menuTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTemperatureActionPerformed(evt);
            }
        });
        menuConvert.add(menuTemperature);

        menuDollar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        menuDollar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paper-currency-icon.png"))); // NOI18N
        menuDollar.setText("Dollar To IDR");
        menuDollar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDollarActionPerformed(evt);
            }
        });
        menuConvert.add(menuDollar);

        menuDoge.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        menuDoge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dogecoin-DOGE-icon.png"))); // NOI18N
        menuDoge.setText("Doge To IDR");
        menuDoge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDogeActionPerformed(evt);
            }
        });
        menuConvert.add(menuDoge);

        menuPertamina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        menuPertamina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/47-fuel-icon.png"))); // NOI18N
        menuPertamina.setText("Pertamina");
        menuPertamina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPertaminaActionPerformed(evt);
            }
        });
        menuConvert.add(menuPertamina);

        jMenu1.add(menuConvert);
        jMenu1.add(jSeparator6);

        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-application-exit-icon.png"))); // NOI18N
        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        menuEdit.setText("Edit");

        menuUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        menuUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Undo-icon.png"))); // NOI18N
        menuUndo.setText("Undo");
        menuEdit.add(menuUndo);

        menuRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        menuRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Redo-icon.png"))); // NOI18N
        menuRedo.setText("Redo");
        menuEdit.add(menuRedo);
        menuEdit.add(jSeparator1);

        menuCopy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/copy-icon.png"))); // NOI18N
        menuCopy.setText("Copy");
        menuEdit.add(menuCopy);

        menuCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuCut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cut-icon.png"))); // NOI18N
        menuCut.setText("Cut");
        menuEdit.add(menuCut);

        menuPaste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menuPaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Paste-icon.png"))); // NOI18N
        menuPaste.setText("Paste");
        menuEdit.add(menuPaste);

        menuDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        menuDelete.setText("Delete");
        menuEdit.add(menuDelete);
        menuEdit.add(jSeparator4);

        menuFind.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menuFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Start-Menu-Search-icon.png"))); // NOI18N
        menuFind.setText("Find");
        menuEdit.add(menuFind);

        jMenuBar1.add(menuEdit);

        menuHelp.setText("Help");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Help-icon.png"))); // NOI18N
        jMenuItem2.setText("Help Content");
        menuHelp.add(jMenuItem2);

        menuUpdate.setText("Check for Updates");
        menuHelp.add(menuUpdate);

        menuReport.setText("Report Issue");
        menuHelp.add(menuReport);

        menuAbout.setText("About");
        menuHelp.add(menuAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cryptoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cryptoButtonActionPerformed
         new DogeToIDR().setVisible(true);
    }//GEN-LAST:event_cryptoButtonActionPerformed

    private void currencyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyButtonActionPerformed
         new DollarToIDR().setVisible(true);
    }//GEN-LAST:event_currencyButtonActionPerformed

    private void menuPertaminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPertaminaActionPerformed
         new RupiahToPertamina().setVisible(true);
    }//GEN-LAST:event_menuPertaminaActionPerformed

    private void temperatureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureButtonActionPerformed
         new Temperture().setVisible(true);
    }//GEN-LAST:event_temperatureButtonActionPerformed

    private void temperatureButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureButton2ActionPerformed
         new RupiahToPertamina().setVisible(true);
    }//GEN-LAST:event_temperatureButton2ActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
         this.dispose();
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuDogeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDogeActionPerformed
         new DogeToIDR().setVisible(true);
    }//GEN-LAST:event_menuDogeActionPerformed

    private void menuDollarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDollarActionPerformed
         new DollarToIDR().setVisible(true);
    }//GEN-LAST:event_menuDollarActionPerformed

    private void menuTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTemperatureActionPerformed
        new Temperture().setVisible(true);
    }//GEN-LAST:event_menuTemperatureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cryptoButton;
    private javax.swing.JButton currencyButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelMataUang;
    private javax.swing.JLabel labelPertamina;
    private javax.swing.JLabel labelSuhu;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenu menuConvert;
    private javax.swing.JMenuItem menuCopy;
    private javax.swing.JMenuItem menuCut;
    private javax.swing.JMenuItem menuDelete;
    private javax.swing.JMenuItem menuDoge;
    private javax.swing.JMenuItem menuDollar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuExport;
    private javax.swing.JMenuItem menuFind;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuImport;
    private javax.swing.JMenuItem menuNew;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenuItem menuPaste;
    private javax.swing.JMenuItem menuPertamina;
    private javax.swing.JMenuItem menuRedo;
    private javax.swing.JMenuItem menuReport;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuTemperature;
    private javax.swing.JMenuItem menuUndo;
    private javax.swing.JMenuItem menuUpdate;
    private javax.swing.JButton temperatureButton;
    private javax.swing.JButton temperatureButton2;
    // End of variables declaration//GEN-END:variables
}
